"""Render a run into ``report.md`` (human) and ``report.json`` (auditable).

The JSON sidecar carries the full FinalReport plus provenance and coverage gaps,
so a reviewer can trace every number back to a source record (DESIGN_PROMPT §10).
"""

from __future__ import annotations

import json
from datetime import datetime
from pathlib import Path

from fra.blackboard import Blackboard
from fra.models import CriticNote, FinalReport


def build_final_report(bb: Blackboard, outstanding: list[CriticNote] | None = None) -> FinalReport:
    """Assemble a :class:`FinalReport` from the draft and plan on the board."""
    if bb.draft is None or bb.plan is None:
        raise ValueError("cannot build final report without a draft and an approved plan")
    draft = bb.draft
    return FinalReport(
        run_id=bb.run_id,
        question=bb.plan.question,
        plan=bb.plan,
        sections=draft.sections,
        figures=draft.figures or bb.figures,
        citations=draft.citations,
        limitations=draft.limitations,
        outstanding_critic_notes=outstanding or [],
    )


def render_markdown(final: FinalReport, bb: Blackboard) -> str:
    lines: list[str] = []
    lines.append(f"# Fisheries Research Report - run `{final.run_id}`")
    lines.append("")
    lines.append(f"**Question:** {final.question}")
    lines.append("")
    lines.append(f"*Generated: {final.generated_at.isoformat()}*")
    lines.append("")

    # Plan summary
    plan = final.plan
    lines.append(
        "**Scope:** "
        + ", ".join(t.scientific_name for t in plan.taxa)
        + " | areas "
        + ", ".join(a.fao_area for a in plan.areas)
        + (f" | {plan.time_range.start_year}–{plan.time_range.end_year}" if plan.time_range else "")
    )
    lines.append("")

    # Figures gallery
    if final.figures:
        lines.append("## Figures")
        lines.append("")
        for fig in final.figures:
            lines.append(f"![{fig.title}]({_fig_path(fig.path)})")
            lines.append("")
            lines.append(f"*Figure {fig.id}: {fig.caption}*")
            lines.append("")

    # Body sections
    for section in final.sections:
        lines.append(section.to_markdown())

    # Outstanding critic notes (if shipped despite unresolved notes)
    if final.outstanding_critic_notes:
        lines.append("## Outstanding review notes")
        lines.append("")
        lines.append(
            "_The Critic did not fully clear this draft within the revision cap; "
            "the following notes remain open:_"
        )
        lines.append("")
        for n in final.outstanding_critic_notes:
            loc = f" ({n.section_title})" if n.section_title else ""
            lines.append(f"- **{n.severity}/{n.category}**{loc}: {n.message}")
        lines.append("")

    # Citations table
    if final.citations:
        lines.append("## Citations")
        lines.append("")
        lines.append("| Marker | Kind | Reference ID | Detail |")
        lines.append("|---|---|---|---|")
        for c in final.citations:
            lines.append(f"| {c.marker} | {c.kind} | `{c.ref_id}` | {c.detail or ''} |")
        lines.append("")

    # Data sources / provenance
    lines.append("## Data Sources")
    lines.append("")
    if bb.provenance:
        lines.append("| Source | Query/URL | Retrieved | # records |")
        lines.append("|---|---|---|---|")
        for p in bb.provenance:
            lines.append(
                f"| {p.source} | {p.url_or_query} | {p.retrieved_at.date()} | {len(p.record_ids)} |"
            )
        lines.append("")
    if bb.coverage_gaps:
        lines.append("### Coverage gaps")
        lines.append("")
        for g in bb.coverage_gaps:
            lines.append(
                f"- **{g.domain}**: {g.detail}"
                + (f" (connector: {g.connector})" if g.connector else "")
            )
        lines.append("")

    lines.append("---")
    lines.append("")
    lines.append(
        "_Generated by Fisheries Research Agents. Every quantitative claim is "
        "grounded in a cited source record; see `report.json` for the full "
        "machine-readable audit trail._"
    )
    lines.append("")
    return "\n".join(lines)


def write_report(
    bb: Blackboard, out_dir: str | Path, *, outstanding: list[CriticNote] | None = None
) -> Path:
    """Write ``report.md`` and ``report.json`` into ``out_dir``; return the dir."""
    out = Path(out_dir)
    out.mkdir(parents=True, exist_ok=True)
    final = build_final_report(bb, outstanding)
    bb.final = final

    (out / "report.md").write_text(render_markdown(final, bb), encoding="utf-8")

    sidecar = {
        "final_report": final.model_dump(mode="json"),
        "provenance": [p.model_dump(mode="json") for p in bb.provenance],
        "coverage_gaps": [g.model_dump(mode="json") for g in bb.coverage_gaps],
        "analyses": [a.model_dump(mode="json") for a in bb.analyses],
        "record_counts": {
            "landings": len(bb.landings),
            "assessments": len(bb.assessments),
            "covariates": len(bb.covariates),
            "references": len(bb.references),
        },
    }
    (out / "report.json").write_text(
        json.dumps(sidecar, indent=2, default=_json_default), encoding="utf-8"
    )
    return out


def _fig_path(path: str) -> str:
    # figures are written under <out>/figures/; markdown lives at <out>/report.md
    return f"figures/{Path(path).name}"


def _json_default(o: object) -> str:
    if isinstance(o, datetime):
        return o.isoformat()
    return str(o)
